FROM python:3.12.10-slim

RUN apt update \
 && apt install --no-install-recommends -y git curl nodejs npm \
 && npm install -g @openai/codex \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ADD pyproject.toml .
ADD requirements.txt .
ADD docs docs
RUN pip install --no-cache-dir . && rm pyproject.toml requirements.txt

ENV PYTHONPATH=/app
ADD pr_agent pr_agent

ENTRYPOINT ["python", "pr_agent/cli.py"]
